# Generated by Django 2.2.3 on 2020-01-14 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorNumber', models.CharField(choices=[('1', 'Ground Level'), ('2', '2nd Level'), ('3', '3rd Level'), ('4', '4th Level'), ('5', '2nd Level'), ('6', '2nd Level'), ('7', '2nd Level'), ('8', '2nd Level'), ('9', '2nd Level')], max_length=2)),
                ('roomNumber', models.CharField(choices=[('01', 'Unit 1'), ('02', 'Unit 2'), ('03', 'Unit 3'), ('04', 'Unit 4'), ('05', 'Unit 5'), ('06', 'Unit 6'), ('07', 'Unit 7'), ('08', 'Unit 8'), ('09', 'Unit 9'), ('10', 'Unit 10'), ('11', 'Unit 11')], max_length=2)),
                ('bedsNumber', models.PositiveSmallIntegerField(choices=[(1, '1 Bedroom'), (2, '2 Bedrooms'), (3, '3 Bedrooms'), (4, '4 Bedrooms')])),
                ('unitNumber', models.CharField(editable=False, max_length=4)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-unitNumber'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default='2020-01-14')),
                ('endDate', models.DateField(default='2020-01-14')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelApp.Room')),
            ],
        ),
    ]
