# Generated by Django 2.2.3 on 2020-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-room']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='endDate',
            field=models.DateField(default='2020-01-18'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startDate',
            field=models.DateField(default='2020-01-18'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floorNumber',
            field=models.CharField(choices=[('1', 'Ground Level'), ('2', '2nd Level'), ('3', '3rd Level'), ('4', '4th Level'), ('5', '5th Level'), ('6', '6th Level'), ('7', '7th Level'), ('8', '8th Level'), ('9', '9th Level')], max_length=2),
        ),
    ]
