# Generated by Django 2.2.3 on 2020-01-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_auto_20200118_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomNumber',
            field=models.CharField(choices=[('01', 'Unit 1'), ('02', 'Unit 2'), ('03', 'Unit 3'), ('04', 'Unit 4'), ('05', 'Unit 5'), ('06', 'Unit 6'), ('07', 'Unit 7'), ('08', 'Unit 8'), ('09', 'Unit 9'), ('10', 'Unit 10'), ('11', 'Unit 11'), ('12', 'Unit 12')], max_length=2),
        ),
    ]
