# Generated by Django 2.2.3 on 2020-01-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0003_auto_20200118_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='endDate',
            field=models.DateField(default='2020-01-20'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startDate',
            field=models.DateField(default='2020-01-19'),
        ),
    ]
